
try2.erl:33: Function run3/2 has no local return
